Add custom docker entrypoint

diff --git a/dockerfiles/build/docker-entrypoint b/dockerfiles/build/docker-entrypoint
--- a/dockerfiles/build/docker-entrypoint
+++ b/dockerfiles/build/docker-entrypoint
@@ -6,9 +6,30 @@ php artisan config:cache
 php artisan route:cache
 php artisan view:cache
 
-# first arg is `-f` or `--some-option`
-if [ "${1#-}" != "$1" ]; then
-    set -- php-fpm "$@"
-fi
+role=${ROLE:-api}
 
-exec "$@"
+if [ "$role" = "api" ]; then
+
+  echo "Running the api..."
+  # first arg is `-f` or `--some-option`
+  if [ "${1#-}" != "$1" ]; then
+    set -- php-fpm "$@"
+  fi
+
+  exec "$@"
+
+elif [ "$role" = "queue-worker" ]; then
+
+  echo "Running queue worker..."
+  exec php artisan queue:work
+
+elif [ "$role" = "scheduler" ]; then
+
+  #    Not implemented
+  echo "Running scheduler..."
+  exit 1
+
+else
+  echo "Could not match the container role \"$role\""
+  exit 1
+fi
